services:
  spring-boot-app:
    build:
      context: ./management
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://maria-app:3306/educationsystemdb

    ports:
      - "8080:8080"
    networks:
      - team1network

  vue-app:
    build:
      context: ./teamprojectvue
    ports:
      - "5173:5173"

  maria-app:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=1234
    ports:
      - "3306:3306"
    networks:
      - team1network

networks:
  team1network:
    driver: bridge
